OPENAI_API_KEY = "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"
LEONARDO_API_KEY = "498b4126-dec0-4dba-b259-7d7d31d1c37e"
